{% set version = "0.11.0" %}

package:
  name: scp
  version: {{ version }}

source:
  url: https://github.com/jbardin/scp.py/archive/v{{ version }}.tar.gz
  sha256: 3b5335d076fc7ba6bf51d509443f8a5009139e1784ab69cd5d9ec62f176c33bc

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - paramiko
  run:
    - python
    - paramiko

test:
  imports:
    - scp

about:
  home: https://github.com/jbardin/scp.py.git
  license: LGPL-2.1
  license_file: LICENSE.txt
  license_family: LGPL
  dev_url: https://github.com/jbardin/scp.py
  doc_url: https://github.com/jbardin/scp.py
  summary: Pure python scp module for paramiko

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
