{% set version = "0.12.1" %}

package:
  name: scp
  version: {{ version }}

source:
  url: https://github.com/jbardin/scp.py/archive/v{{ version }}.tar.gz
  sha256: d04bd7b55503535f6be752af7ecdf9b4320dea2977f3b8615e61e58f7c31c5c6

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - paramiko
  run:
    - python
    - paramiko

test:
  imports:
    - scp

about:
  home: https://github.com/jbardin/scp.py.git
  license: LGPL-2.1
  license_file: LICENSE.txt
  license_family: LGPL
  dev_url: https://github.com/jbardin/scp.py
  doc_url: https://github.com/jbardin/scp.py
  summary: Pure python scp module for paramiko

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
