# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "IxoIvueQL8jtnkEKtRa/KR/iXchhD2y1zL/Ae/oQbPkBywxQr+tviw25h4FAnHdOKCruKAW1HQA4pGychVLEdZ7OxvIxGjvfUbhaz5OWhxJ2eX+3zWZ3dyn9ohroSGb1PN85zGVGZAF/csnrjE9KaCWbejr6Wyj4yQ5Sv+Ou1OajZgJXG866+ONiNxpgZfBcCP+1xouN+Iy80/1mjV1WtJ53IEmKIrekGTgmVAX8oW8HFo3WZi/PfjNbjbzpiunwfbI5b2Y8Dq5cbJ6ONpMCxKk/ad+O1AnahuNdN07LB5hseXITH08zXBKdfIAn+vlG3SgTCK/6jiGoBuiH4yMfDLhDgUn0nun3G0dDFlrE5SV1y5hyT9KzFIRUAP3YMJtsnuDXQvIKa7zvnOSVHyn4jKnIrUH9x0E+i+9D+r346ul0KrIbCyhKVz+QCmxhUKZb/IPDIEyP/hYHq2cfLaaBv0YYjTFUg1aTBS6x9JR+Gxp60WNuc31dyolT6xYsBhoSlJwqsJySCruKzpHOQ1rP8wIMJpCvRenFt+d+CIxOUBEEO7S7QWNJ1eGJuq7ttU2P5DQWGHL1sM5K7Mm/xUw5bFGKDcYn7TLl4IuOc30zoAEBPlVlz4XEeYnu1X1Z4s0ia9pa6mlEbEPd8hPkZjGtmm3N0xNGWS8qW55/3nwV0GY="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
