# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "CFCbc5LO4fF7lcZVxdQQGlZ/NpNOo1cKzjDrqGb/PWp93Q4aE44/a39TptOv0IGDGYTb0Nd4pheIGUToPME2MEXtElOUn/uGAqSEtS9etpYbXmaH6tL4jMGqbRf5sQKQtbLS8yYExr92R73lnnop+zDuog3fYxbWkcf3MqIvx+HcqXjWrXo8o9/wTqRI+L+oSjkHqS34CcXmR7G/Qq4lm8wM1dRR6tkuB267pyMOx4xjRxat9/0f7P0S3twBa9BoLWon/p7oPua9YBJ/xeraNurYbxUwlPLwZkXqI86+ZbNyF+WpyLmicdnuJhBjJo4Mi7S3uxjPq1yXSHZAXtH0X7yhzp678IF1jwnny8BzUi+xw92fqJqfX0BlMOqIBt8nLv+BylE0es9+0juQo5f0A16eue1GbNnL5k6n+9YuBqikru/cw540oY1h+MovtHddiyRs4JUDS1+DaklBE1Pk5VOG2VhpB5e64iPIDvWlXeJvHocNTrGc9oSBx+j9qhVo6q00oqm9aFvura47RexP1duw6QBGCkXxexrB7t2Lvdg7ZwxaTOAmIOudioKLBIu1XQuIaVp062sgxJBjwzUxY5FOvhrmcgspZv5sqWLvFMX9ZBKy9Y1AVqrq4hrzm89ECQN9Y4OgNBLOqJsko3cRLlajAw8WjJW2Wg88CAudy/Y="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
