travis:
  secure:
    BINSTAR_TOKEN: IuYdm6R2AWTozGPjFl2D9NVMG2RxHNsIYR+2lTcXPDDXoFEPC+A8vHjQoDk9w+fxjguo4EVmnYijL0b7xPYS2TpPeyeFa4fVTYIdocE55qkxgd0TBoMXnOwHVUnFk5rJPkQwH25NlRD76TYlvd0P0ymC0AYSIN4NnDs5NoXHjzIolWww2piICQ/BJiBERPTLlzGLX9tg8LMnpB1bCItrv0h1H8QQdnkwcgy4HSXAyEXWYogU2YbNbh99kDHWQ3BNvL3DIcMvloArO9n3UhMO/0LAOwKfxApsj0grIvDvBsKc2QEKKnnjq4YbdN8ydgFocfmRMTsuQTtxvFEQhl6208M4UGt2h3Snxb+JxWVMS2usql4fHKjNkZQ23GanjL9+if3GuMCjpLTHAtra5QUg+F7oVLUeNAdH9CPwGR7EhjiEknqcnQHboLRIHvy4xC7mC9q5yBTyztgmLKRKu3ILNOexpzUL82xhx6Ri6UIZI/pSsLjFmYllZVFRrIwp3EU8NGtW29NErKEqhSqq3uvU8XPTchweIV2DLi8AGew+xAehA4geliBi+mErbEJ/xBhDMTb5tF/6mr3Jf+qXIYz6GMSlaDnoSfDfraVVWRFUJrCKF9MFcCxM32Gi/flCSdO+9+Pvb3679H7ibQDqYyWG0l9G/MnXthAcmvcu7tAB4GQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
