travis:
  secure:
    BINSTAR_TOKEN: IxoIvueQL8jtnkEKtRa/KR/iXchhD2y1zL/Ae/oQbPkBywxQr+tviw25h4FAnHdOKCruKAW1HQA4pGychVLEdZ7OxvIxGjvfUbhaz5OWhxJ2eX+3zWZ3dyn9ohroSGb1PN85zGVGZAF/csnrjE9KaCWbejr6Wyj4yQ5Sv+Ou1OajZgJXG866+ONiNxpgZfBcCP+1xouN+Iy80/1mjV1WtJ53IEmKIrekGTgmVAX8oW8HFo3WZi/PfjNbjbzpiunwfbI5b2Y8Dq5cbJ6ONpMCxKk/ad+O1AnahuNdN07LB5hseXITH08zXBKdfIAn+vlG3SgTCK/6jiGoBuiH4yMfDLhDgUn0nun3G0dDFlrE5SV1y5hyT9KzFIRUAP3YMJtsnuDXQvIKa7zvnOSVHyn4jKnIrUH9x0E+i+9D+r346ul0KrIbCyhKVz+QCmxhUKZb/IPDIEyP/hYHq2cfLaaBv0YYjTFUg1aTBS6x9JR+Gxp60WNuc31dyolT6xYsBhoSlJwqsJySCruKzpHOQ1rP8wIMJpCvRenFt+d+CIxOUBEEO7S7QWNJ1eGJuq7ttU2P5DQWGHL1sM5K7Mm/xUw5bFGKDcYn7TLl4IuOc30zoAEBPlVlz4XEeYnu1X1Z4s0ia9pa6mlEbEPd8hPkZjGtmm3N0xNGWS8qW55/3nwV0GY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
