travis:
  secure:
    BINSTAR_TOKEN: DvgYnXVxnsYECC75f0rhB1mimwowQe8p3trCctQ30EF+fiXFEAodGGAVW9LxLN13TN+VJF0tUNxaan3694q26PkJhgyRh4OWDa8u2qGLj1rDXwyb8S3jWvMK5k4miOMtA1la7eHtbveNy4lu/FpJ4laM2fTQganQpL/eWoWa2+E8bFT+nuDjjH27NwiacQfxVWFLcGESOdPPPgQbtjCG4e1svEjf+hqVOktGWSBZACFOpZe1CVpOoKKLCrIUyRZn5BLFSwDUED6yEGazVAGrYMAIA7FMACm6yi1lCXjAsRxWfq6x6h0vIbCzcLJwaVhtbCYP4N2n7N28Iq/9890xrpIuWr4dF0Uzi7nTdiAO/xA80Qwx4JnlRHOuyGXd+5wTgRMmFt3mQ9WNvfNGl8eLCMHQFBeUOunDJ8LEfJOl5JontUYmDDoMzBlzVLjqm26p+BfP+ARqglL85p96NCxRFltE2+YCqrHCefL1l9RfX0OnhARYqwquAMoMCBdaJqbAXTdj3jFmHTWa56I7Ridi74ZIhJCb/2XwBYMqBk8592doNsdaUMMMON+UkjWX36Zn5dbj99NZoesPngBwd1E5c6G5ND5ZFpVylAFGFHqk7QFh5zEPzTX5WqKZcjA9GC0VWU/X593r0OU1yB81YOdKEWA4BEIKeXLsnS4kh5dWMz4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
