travis:
  secure:
    BINSTAR_TOKEN: WNwNgi+QrIQ9QiCDIS8jrfmNIiY4mdHfPgU/QHrE/mfc28bEymydHE9HRFH4WU1H7IEMczct1Isx/7xbjd5Vd2WYUZKJY8OpIKx2Z4vUDg1KYozmlHKyVM7Mc65YGCShbKNqtGy9OJRyNYF5nhYTw57JrFVdKzkvd2PSFzWZGXMsl0KgQjvCf/EcUp4ky4Nh6NbcetImfI/6jrlQmTcL2WFR6Ht9kOP2btAhs7DMlo72UeqJSNg0Ui0dh8D+9PNmi+5m+7RsdjnkyH8l2F++R/Pz3Vv1al1GGjkJFXeVpmfa4Mlwyy5pldfto7nqkTBw9Ksctdyvaxfb9FPuKHAt2eNAwfef0Z8qN226qDqPE9psPqe9HsBYQ2gcTTfvfOyl45MBGYRnVdd5pvT04yjRxc0wO4gc4lAaF8UI5l+CJDgmTEe/T0futZ6cdCTayunoFf+KS6H2Tj7WRG+cVRiBq+AzNRk+fjkAIITv7s5xd0RWCRFKwMH2mQQ7IfAGpuijUEzJQTqGGBVnxyv9X20onJP4q/f9VwTXwGUTzPHGdqz4lmuk67P17oDDphBRQ467S0gPZarrLcYHrLOzd63trBORzBloV2KjhhwUbQL1UpGXxmh2G2TS/2aWjaw9eTcNFuECJc4FyBOucoZ+uRPLQAbyX3xWY9pzyOcbroNR0uw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
