travis:
  secure:
    BINSTAR_TOKEN: hxrMzuCZMUTsjt83uvFo6FitOhiD1cpEdZQkyIKSpMQf1F+uID/z8PK6++D4/VXqCU/rgXhfazxgFfTlhMXgWTy2MfLNS7XKxXoUBDQrHx9OzYo1ftEBVUY1LlBGpv0ZVgemEGrEHsBH3tHpEqZfUfJUCEQWY2p8gWys9xqrEicreMd5Hw8vBFQ/ogIx61qEj9wVeXesLtomf+3ruHeQzuXmavmCjADVFeiCYUNwTp0/4T7XLztS1dr2eFtOJEW0tTYOmbFqSdF5n2Zw9gBEQV9lYts9NeCMkZGvqOqArGJoW8qqVqKHEiZ5G13JDGX+DPkfRVt5MUKAQcXrjkFL6H+ApvHojjzYfxwVf1XR0w3s0Ol3k7JyVtd3PRpeqE8omHtnOKG0ghvKZSwAGaUkfhgqLL78joEkVjBA1qyI8s//0FZQbuKxJyC2Iud8qlefjxffCjr0uwQjHMKU/zW6O8aDWkd/v4Wja+3Bsaqy2TTdHXDukDkI+QZJPLf10sCyaCh9Kd5I1Uy3yiqPhdqh/VsliVSPWIWGIbDixpsuCUImdebr5LEaBXz7YYqcJ2WcjbXP0FXh4CwaEhNzK7YdxCffgXeh/7Hc4BymcEAbhZj1ay5U6qolyLIczqKHQPQz+R/cjAIFmsHlMLcAksmgZJJpNzoOAdesf8C3a/E53Ag=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
