travis:
  secure:
    BINSTAR_TOKEN: CFCbc5LO4fF7lcZVxdQQGlZ/NpNOo1cKzjDrqGb/PWp93Q4aE44/a39TptOv0IGDGYTb0Nd4pheIGUToPME2MEXtElOUn/uGAqSEtS9etpYbXmaH6tL4jMGqbRf5sQKQtbLS8yYExr92R73lnnop+zDuog3fYxbWkcf3MqIvx+HcqXjWrXo8o9/wTqRI+L+oSjkHqS34CcXmR7G/Qq4lm8wM1dRR6tkuB267pyMOx4xjRxat9/0f7P0S3twBa9BoLWon/p7oPua9YBJ/xeraNurYbxUwlPLwZkXqI86+ZbNyF+WpyLmicdnuJhBjJo4Mi7S3uxjPq1yXSHZAXtH0X7yhzp678IF1jwnny8BzUi+xw92fqJqfX0BlMOqIBt8nLv+BylE0es9+0juQo5f0A16eue1GbNnL5k6n+9YuBqikru/cw540oY1h+MovtHddiyRs4JUDS1+DaklBE1Pk5VOG2VhpB5e64iPIDvWlXeJvHocNTrGc9oSBx+j9qhVo6q00oqm9aFvura47RexP1duw6QBGCkXxexrB7t2Lvdg7ZwxaTOAmIOudioKLBIu1XQuIaVp062sgxJBjwzUxY5FOvhrmcgspZv5sqWLvFMX9ZBKy9Y1AVqrq4hrzm89ECQN9Y4OgNBLOqJsko3cRLlajAw8WjJW2Wg88CAudy/Y=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
